export const JWT_PUBLIC_KEY = process.env.JWT_PUBLIC_KEY || `-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAt0ieIA2NVxPyPsaOEnVo
jhaR8ERyuCZTBFgTbaRs/0ugkUETW4FWmnfQBz6HCOZYge5nhOjzwEVMSNB2zlig
0FHPguTbRQ8ZLl5yw04GMf89pLSzgnIPv5B/qUWk4l4r0EsA8d6eqr09zjyisqWQ
E3iS5NycJQWE9p/yIE+LKYdKWNxgSfxUgbFqJPYnTMQywQEYGSEEWNS7zNRS9I9Y
6JhkGh+iNNln1GzjE5yWMswTqYTotGBgFkOT6FmiJ8AUwz4AtBz8AKeatNsX+hRM
ldBqfobtnZ0mHiDbQBk3C59tloSEIEMEMmsuVoPM7srmXfJT9BflcB2vG3WYXJK/
RQIDAQAB
-----END PUBLIC KEY-----
`